# SPDX-License-Identifier: GPL-2.0
# Makefile for mount selftests.
CFLAGS = -Wall \
         -O2

# TEST_PROGS := run_unprivileged_remount.sh run_nosymfollow.sh
TEST_GEN_PROGS := anon-only
TEST_FILES := one-page.img

include ../lib.mk
